version: "2"
services:
  influxdb:
    image: bitnami/influxdb
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_ADMIN_USER_PASSWORD=password123
      - INFLUXDB_DB=my_database
      - INFLUXDB_USER_BUCKET=my_bucket
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      - INFLUXDB_ADMIN_USER_TOKEN=token